// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-RNt00i4j0pDrur6-pd2_MwgAHspxkx0',
    appId: '1:428843454491:android:fc71e9e3bfe26bc8c3e8be',
    messagingSenderId: '428843454491',
    projectId: 'restaurantapp-5ad53',
    storageBucket: 'restaurantapp-5ad53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcFsT2AEgK5WILuaX8LOcQaPM6U7_sD_w',
    appId: '1:428843454491:ios:d8456d897d3a2052c3e8be',
    messagingSenderId: '428843454491',
    projectId: 'restaurantapp-5ad53',
    storageBucket: 'restaurantapp-5ad53.appspot.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcFsT2AEgK5WILuaX8LOcQaPM6U7_sD_w',
    appId: '1:428843454491:ios:d8456d897d3a2052c3e8be',
    messagingSenderId: '428843454491',
    projectId: 'restaurantapp-5ad53',
    storageBucket: 'restaurantapp-5ad53.appspot.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWW1A_A2VShB8_wvFeiwVKIheLZN9m75o',
    appId: '1:428843454491:web:2a028297addcb5cdc3e8be',
    messagingSenderId: '428843454491',
    projectId: 'restaurantapp-5ad53',
    authDomain: 'restaurantapp-5ad53.firebaseapp.com',
    storageBucket: 'restaurantapp-5ad53.appspot.com',
    measurementId: 'G-E8Q4D2HHTB',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWW1A_A2VShB8_wvFeiwVKIheLZN9m75o',
    appId: '1:428843454491:web:4e189e9251a361c6c3e8be',
    messagingSenderId: '428843454491',
    projectId: 'restaurantapp-5ad53',
    authDomain: 'restaurantapp-5ad53.firebaseapp.com',
    storageBucket: 'restaurantapp-5ad53.appspot.com',
    measurementId: 'G-V3R31HZ8JD',
  );

}